### ISSUE TITLE
representing as a linked list is an implementation detail

### ISSUE THREAD

**Issue by kylesferrazza** [xbrett/a1-part2#2]
Per https://piazza.com/class/k51bluky59n2jr?cid=317_f3:

> Q: What if there is already an implementation in the spec? A: Let the spec team know that if they don't remove it, they will lose points. Further, they need to purge it from the history. `git rm` is not nearly enough. Also, please write up this incident as a part of your report. 

and

> [If] these are fields that are merely contingent to your particular method of implementation of their spec, then no, they are implementation details and do not belong in the spec

So please remove `node.h`, and all fields from `Queue`.

**Comment by xbrett** [comment]
Thanks, they have been removed.
