### ISSUE TITLE
Strings implicitly become Objects

### ISSUE THREAD

**Issue by kylesferrazza** [xbrett/a1-part2#3]
If I `push` a `String *`, I expect to be able to `pop` a `String *`, and not just an `Object *`, so I can continue to use the `String *` without casting.

**Comment by kylesferrazza** [comment]
One possible way this could be accomplished is with a second class strictly for `StringQueue`s, which has the methods:
- `String* peek`
- `String* pop`

Also, the current `void push(String* s)` method essentially serves no function since any `String *` can be passed as an argument to `void push(Object* o)`, since `String` extends `Object`.

**Comment by xbrett** [comment]
Thank you for the feedback. I'm going to move forward making these changes to improve the usability of queues with Strings.  I have the new class written, and will work on updating the tests this evening.

**Comment by xbrett** [comment]
Updated the tests, closing this issue.
